[package]
name = "rust-samtools-genome-view"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
colorize = "0.1.0"
rayon = "1.10.0"
